FROM php:7.1-apache

# Install mysql driver
RUN apt-get update \
	  && echo 'deb http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list \
	  && echo 'deb-src http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list \
  && apt-get install -y gnupg wget

RUN apt-get install -y zlib1g-dev libpng-dev

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Enable mod_rewrite
RUN a2enmod rewrite
RUN a2enmod mime
RUN a2enmod ssl

RUN apt-get install -y openssl

RUN apt-get install -y libfontconfig1 libxrender1 libxtst6
