version: '2'

services:
    php:
        build:
          context: .
          dockerfile: Dockerfile-php-apache
        volumes:
            - ./:/var/www/html/
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - mysql

    mysql:
        image: mysql:5.6
        command: --max_allowed_packet=16777216
        env_file:
            - .env
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "3307:3306"
